apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-core-keeper-server.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-core-keeper-server.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "k8s-core-keeper-server.labels" . | nindent 8 }}
    spec:
      containers:
        - name: corekeeper
          image: escaping/core-keeper-dedicated
          imagePullPolicy: Always
          env:
            - name: WORLD_INDEX
              value: "0"
            - name: WORLD_NAME
              value: Cillian Murphy The Core
            - name: WORLD_SEED
              value: "0"
            - name: GAME_ID
              value: "9sgSTF4D5rkT9J8nf4cueafS9AZ9"
            - name: DATA_PATH
              value: ""
            - name: MAX_PLAYERS
              value: "10"
            - name: DISCORD
              value: "1"
            - name: DISCORD_HOOK
              value: "https://discord.com/api/webhooks/1285624982159753310/fN1luHKiHA1aRKr1NNXQUhcGhFqLUMvuN4rcbqmZZmmNeAyCkf_K9zm6uzGHYuVX8kW4"
            - name: SEASON
              value: ""
          ports:
            - containerPort: 27015
              protocol: UDP
              name: gameudp
          volumeMounts:
            - name: data
              mountPath: /home/steam/core-keeper-data
              # mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "k8s-core-keeper-server.fullname" . }}

